added some aetheryte functions, changed GetQuestIDByName a little
Jaksuhn/SomethingNeedDoingLegacy pull request #229
Opened 2024-10-18 08:37 UTC by pot0to

- moved `GetAetheryteList` under WorldStateCommands
- added `GetAetherytesInZone`, `GetAetheryteName`, `GetAetheryteRawXPos`, `GetAetheryteRawYPos`
- made some fixes to `GetQuestIDByName` to include beast tribe quests with icons in the name, such as " Money Makes the Moon Go Round"

2024-10-19 08:12 UTC, Jaksuhn requested changes

2024-10-19 08:12 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/CharacterStateCommands.cs
> -    public List<uint> GetAetheryteList() => Svc.AetheryteList.Select(x => x.AetheryteId).ToList();
This *is* a CharacterStateCommand. The aetheryte list is tied to your character because it's what you've unlocked

2024-10-19 08:12 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
Don't change my regex. I don't know the full consequences of it and "it makes my one thing work" isn't a reason. Filter out special characters from your query first.

2024-10-19 08:12 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +        return matchingRows.FirstOrDefault()?.RowId;
this won't return null

2024-10-19 10:04 UTC, pot0to commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
The problem is that the value of `y` here is the value from sheets, not my input. Since the icon is part of the quest name in sheets, that means whatever I try to input will be attempting to match against `\b + some icon`. Since icons do not have word boundaries, this will always return false for any quest with a name that starts with an icon, which includes all beast tribe quests and possibly some other quests as well. The alternative is that I could swap x and y in the line where you call this (but I was worried that would have even more consequences), or the hacky way is that I can prepend my input with a fake word boundary... which I'm not really sure how to do?

2024-10-19 10:17 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
Then you need to get x such that it actually includes the full name, or better, **stop trying to do name matches**. I have no idea why you guys are hellbent on doing it that way. I remember having the regex be that way for a reason, and I do not want to change functionality on how it works because I don't remember the consequences and don't want to deal with that problem down the road.

2024-10-19 10:51 UTC, pot0to commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
There does not exist any value of `x` that will make this function return true because the `y` side _is not valid regex_ if the value of `y` coming from sheets starts with an icon. If you just want to mark this as a "won't fix", then I'll accept that.

![image](https://github.com/user-attachments/assets/6981cbf9-83dc-426c-8611-e4f6581dd97e

2024-10-19 11:31 UTC, pot0to commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
As for avoiding name matches: I’m trying to open up the beast tribe SelectIconString, accept all quests, yield to Questionable, then wait until all those quests have been completed. I figured GetNodeText(SelectIconString) to read the quest name then calling this function would be the easiest way to track what quests I just accepted. I suppose another way would be to hardcode the list of beast tribe quest ids, then loop through all of them to see which ones have been accepted?

2024-10-19 11:44 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
why do you even care about the node text of the selectstring? Just accept everything then iterate through your quest list and call questionable for each. If at any point you're thinking you need to hardcode lists or especially use names for something, you need to immediately think "there must be a better way of doing this".

2024-10-19 11:49 UTC, pot0to commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
Because I don’t want to call Questionable for every quest in my journal. I want to skip MSQ, leves, other side quests, etc. I ONLY want to wait for the 3 beast tribes I just accepted to complete, then turn off Questionable.

2024-10-19 11:51 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
... which you can obviously filter down to tribal quests

2024-10-19 12:12 UTC, pot0to commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
Am I missing something somewhere? I don't see any existing functions under `QuestCommands` or `CharacterStateCommands` that let me filter for tribal quests. And I dont see any filters in my in-game journal either (I don't have any acceptances left for today, but I think they just show up under the zone name alongside the other sidequests). Or are you saying you would prefer I implement a `GetBeastTribeQuests` function here in C# instead of changing your regex?

2024-10-19 16:40 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
>  Or are you saying you would prefer I implement a GetBeastTribeQuests function here in C# instead of changing your regex?

Yes. I forget if there's any functions for getting active quests, but if there's not then I'd add one for that and for any special filtering you want to do

2024-10-21 00:08 UTC, pot0to commented on SomethingNeedDoing/Misc/Commands/QuestCommands.cs
> +    private static bool IsMatch(string x, string y) => Regex.IsMatch(x, $@"{Regex.Escape(y)}\b");
Aight I added `GetQuestAlliedSociety(uint id)` and `GetAcceptedQuests()`

2024-10-22 07:33 UTC, pot0to commented
Added:
- `GetQuestAlliedSociety(uint id)` and `GetAcceptedQuests()`
- `GetPartyLeadIndex()`

2024-10-22 09:13 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/CharacterStateCommands.cs
> +    public float GetAetheryteRawXPos(uint aetheryteID)
This should be in world state

2024-10-22 09:14 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/CharacterStateCommands.cs
> +    }
since these don't access aetheryte list, they should be in world state

2024-10-22 09:14 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/CharacterStateCommands.cs
> +    }
this should be in utils

2024-10-22 09:16 UTC, Jaksuhn commented on SomethingNeedDoing/Misc/Commands/CharacterStateCommands.cs
> +    }
also since apparently you can access non simple data types from lua, you could just return a tuple and only have the one function. I would've done that from the start had I known

2024-10-22 09:55 UTC, merged

2024-10-22 09:56 UTC, pot0to commented on SomethingNeedDoing/Misc/Commands/CharacterStateCommands.cs
> +    }
done, values can now be accessed as `x = GetAetheryteRawPos(aetheryteID).Item1`, `y = ...Item2`